### PR TITLE
L10n Language Support

### PR DESCRIPTION
**Pull request by akenejie**
Could you please consider making the extension multilingual for those who use VSCode in non-English environments?
There are some parts of them that are not yet Japanese-enabled, but I have created the basic part of the multilingualization for now.
The Japaneseized parts are the titles of the commands in package.json and the strings in collaboration-room-service.ts.

### CODE REVIEW

**Comment by akenejie** [comment]
To make the extension multilingual, it would have to replace all String in the source code,
"... /package.nls." + vscode.env.language + ".json" reading may be better moved to the root.

**Review by msujew — COMMENTED** [review]
Hey @akenejie,

thanks for looking into this! However, this isn't using the recommended tooling for l10n in VS Code. Please refer to [this repository](https://github.com/microsoft/vscode-l10n) and the appropriate [vscode API documentation](https://code.visualstudio.com/api/references/vscode-api#l10n) to implement this in a maintainable way.

In order to use the API, please raise the required VS Code version to `^1.73.0`.

**Comment by akenejie** [comment]
Then, vscode versions prior to 1.73.0 will no longer be supported, but changed it anyway.

**Comment by msujew** [comment]
@akenejie I've pushed some changes on your branch. Can you please check whether the new japanese localizations are accurate? I've simply used DeepL to translate the english values. In case anything can be improved in the `package.nls.ja.json` or `bundle.l10n.ja.json`, just push it, and then we can merge the PR.

**Comment by akenejie** [comment]
Updated Japanese translation part.

**Review by msujew — APPROVED** [review]
Thanks a lot 👍

**Pull request merged**
